// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: proto/movie/movie.proto

package movie

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Genres) Reset() {
	*x = Genres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Genres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genres) ProtoMessage() {}

func (x *Genres) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genres.ProtoReflect.Descriptor instead.
func (*Genres) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{0}
}

func (x *Genres) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genres) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Production struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LogoPath string `protobuf:"bytes,2,opt,name=logo_path,json=logoPath,proto3" json:"logo_path,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Production) Reset() {
	*x = Production{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Production) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Production) ProtoMessage() {}

func (x *Production) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Production.ProtoReflect.Descriptor instead.
func (*Production) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{1}
}

func (x *Production) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Production) GetLogoPath() string {
	if x != nil {
		return x.LogoPath
	}
	return ""
}

func (x *Production) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MovieMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PosterPath   string        `protobuf:"bytes,3,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	ReleaseDate  string        `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Genres       []*Genres     `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	Homepage     string        `protobuf:"bytes,6,opt,name=homepage,proto3" json:"homepage,omitempty"`
	Overview     string        `protobuf:"bytes,7,opt,name=overview,proto3" json:"overview,omitempty"`
	BackdropPath string        `protobuf:"bytes,8,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	Runtime      int32         `protobuf:"varint,9,opt,name=runtime,proto3" json:"runtime,omitempty"`
	ImdbId       string        `protobuf:"bytes,10,opt,name=imdb_id,json=imdbId,proto3" json:"imdb_id,omitempty"`
	Production   []*Production `protobuf:"bytes,11,rep,name=production,proto3" json:"production,omitempty"`
}

func (x *MovieMessage) Reset() {
	*x = MovieMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieMessage) ProtoMessage() {}

func (x *MovieMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieMessage.ProtoReflect.Descriptor instead.
func (*MovieMessage) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{2}
}

func (x *MovieMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MovieMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieMessage) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *MovieMessage) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *MovieMessage) GetGenres() []*Genres {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MovieMessage) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *MovieMessage) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *MovieMessage) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

func (x *MovieMessage) GetRuntime() int32 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

func (x *MovieMessage) GetImdbId() string {
	if x != nil {
		return x.ImdbId
	}
	return ""
}

func (x *MovieMessage) GetProduction() []*Production {
	if x != nil {
		return x.Production
	}
	return nil
}

type PopularMoviesMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PosterPath  string  `protobuf:"bytes,3,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	ReleaseDate string  `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Overview    string  `protobuf:"bytes,5,opt,name=overview,proto3" json:"overview,omitempty"`
	VoteAverage float32 `protobuf:"fixed32,6,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
}

func (x *PopularMoviesMessage) Reset() {
	*x = PopularMoviesMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopularMoviesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularMoviesMessage) ProtoMessage() {}

func (x *PopularMoviesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularMoviesMessage.ProtoReflect.Descriptor instead.
func (*PopularMoviesMessage) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{3}
}

func (x *PopularMoviesMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PopularMoviesMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PopularMoviesMessage) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *PopularMoviesMessage) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *PopularMoviesMessage) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *PopularMoviesMessage) GetVoteAverage() float32 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

type SearchMoviesMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PosterPath  string  `protobuf:"bytes,3,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	ReleaseDate string  `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	VoteAverage float32 `protobuf:"fixed32,6,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
}

func (x *SearchMoviesMessage) Reset() {
	*x = SearchMoviesMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMoviesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMoviesMessage) ProtoMessage() {}

func (x *SearchMoviesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMoviesMessage.ProtoReflect.Descriptor instead.
func (*SearchMoviesMessage) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{4}
}

func (x *SearchMoviesMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchMoviesMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchMoviesMessage) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *SearchMoviesMessage) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *SearchMoviesMessage) GetVoteAverage() float32 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

type CastMovieMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePath string `protobuf:"bytes,3,opt,name=profile_path,json=profilePath,proto3" json:"profile_path,omitempty"`
	Character   string `protobuf:"bytes,4,opt,name=character,proto3" json:"character,omitempty"`
}

func (x *CastMovieMessage) Reset() {
	*x = CastMovieMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastMovieMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastMovieMessage) ProtoMessage() {}

func (x *CastMovieMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastMovieMessage.ProtoReflect.Descriptor instead.
func (*CastMovieMessage) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{5}
}

func (x *CastMovieMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CastMovieMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CastMovieMessage) GetProfilePath() string {
	if x != nil {
		return x.ProfilePath
	}
	return ""
}

func (x *CastMovieMessage) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

type CrewMovieMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePath string `protobuf:"bytes,3,opt,name=profile_path,json=profilePath,proto3" json:"profile_path,omitempty"`
	Job         string `protobuf:"bytes,4,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *CrewMovieMessage) Reset() {
	*x = CrewMovieMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrewMovieMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrewMovieMessage) ProtoMessage() {}

func (x *CrewMovieMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrewMovieMessage.ProtoReflect.Descriptor instead.
func (*CrewMovieMessage) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{6}
}

func (x *CrewMovieMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CrewMovieMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CrewMovieMessage) GetProfilePath() string {
	if x != nil {
		return x.ProfilePath
	}
	return ""
}

func (x *CrewMovieMessage) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

type VideosMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *VideosMessage) Reset() {
	*x = VideosMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideosMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideosMessage) ProtoMessage() {}

func (x *VideosMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideosMessage.ProtoReflect.Descriptor instead.
func (*VideosMessage) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{7}
}

func (x *VideosMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VideosMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *GetMovieRequest) Reset() {
	*x = GetMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRequest) ProtoMessage() {}

func (x *GetMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{8}
}

func (x *GetMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieMessage *MovieMessage `protobuf:"bytes,1,opt,name=movie_message,json=movieMessage,proto3" json:"movie_message,omitempty"`
}

func (x *GetMovieResponse) Reset() {
	*x = GetMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieResponse) ProtoMessage() {}

func (x *GetMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieResponse.ProtoReflect.Descriptor instead.
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{9}
}

func (x *GetMovieResponse) GetMovieMessage() *MovieMessage {
	if x != nil {
		return x.MovieMessage
	}
	return nil
}

type ListPopularMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPopularMovieRequest) Reset() {
	*x = ListPopularMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPopularMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopularMovieRequest) ProtoMessage() {}

func (x *ListPopularMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopularMovieRequest.ProtoReflect.Descriptor instead.
func (*ListPopularMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{10}
}

type ListPopularMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PopularmovieMessage []*PopularMoviesMessage `protobuf:"bytes,1,rep,name=popularmovie_message,json=popularmovieMessage,proto3" json:"popularmovie_message,omitempty"`
}

func (x *ListPopularMovieResponse) Reset() {
	*x = ListPopularMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPopularMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopularMovieResponse) ProtoMessage() {}

func (x *ListPopularMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopularMovieResponse.ProtoReflect.Descriptor instead.
func (*ListPopularMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{11}
}

func (x *ListPopularMovieResponse) GetPopularmovieMessage() []*PopularMoviesMessage {
	if x != nil {
		return x.PopularmovieMessage
	}
	return nil
}

type ListSearchMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchMovieId string `protobuf:"bytes,1,opt,name=search_movie_id,json=searchMovieId,proto3" json:"search_movie_id,omitempty"`
}

func (x *ListSearchMovieRequest) Reset() {
	*x = ListSearchMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSearchMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSearchMovieRequest) ProtoMessage() {}

func (x *ListSearchMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSearchMovieRequest.ProtoReflect.Descriptor instead.
func (*ListSearchMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{12}
}

func (x *ListSearchMovieRequest) GetSearchMovieId() string {
	if x != nil {
		return x.SearchMovieId
	}
	return ""
}

type ListSearchMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchmovieMessage []*SearchMoviesMessage `protobuf:"bytes,1,rep,name=searchmovie_message,json=searchmovieMessage,proto3" json:"searchmovie_message,omitempty"`
}

func (x *ListSearchMovieResponse) Reset() {
	*x = ListSearchMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSearchMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSearchMovieResponse) ProtoMessage() {}

func (x *ListSearchMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSearchMovieResponse.ProtoReflect.Descriptor instead.
func (*ListSearchMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{13}
}

func (x *ListSearchMovieResponse) GetSearchmovieMessage() []*SearchMoviesMessage {
	if x != nil {
		return x.SearchmovieMessage
	}
	return nil
}

type CastMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *CastMovieRequest) Reset() {
	*x = CastMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastMovieRequest) ProtoMessage() {}

func (x *CastMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastMovieRequest.ProtoReflect.Descriptor instead.
func (*CastMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{14}
}

func (x *CastMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type CastMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CastmovieMessage []*CastMovieMessage `protobuf:"bytes,1,rep,name=castmovie_message,json=castmovieMessage,proto3" json:"castmovie_message,omitempty"`
}

func (x *CastMovieResponse) Reset() {
	*x = CastMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastMovieResponse) ProtoMessage() {}

func (x *CastMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastMovieResponse.ProtoReflect.Descriptor instead.
func (*CastMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{15}
}

func (x *CastMovieResponse) GetCastmovieMessage() []*CastMovieMessage {
	if x != nil {
		return x.CastmovieMessage
	}
	return nil
}

type CrewMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *CrewMovieRequest) Reset() {
	*x = CrewMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrewMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrewMovieRequest) ProtoMessage() {}

func (x *CrewMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrewMovieRequest.ProtoReflect.Descriptor instead.
func (*CrewMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{16}
}

func (x *CrewMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type CrewMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrewmovieMessage []*CrewMovieMessage `protobuf:"bytes,1,rep,name=crewmovie_message,json=crewmovieMessage,proto3" json:"crewmovie_message,omitempty"`
}

func (x *CrewMovieResponse) Reset() {
	*x = CrewMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrewMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrewMovieResponse) ProtoMessage() {}

func (x *CrewMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrewMovieResponse.ProtoReflect.Descriptor instead.
func (*CrewMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{17}
}

func (x *CrewMovieResponse) GetCrewmovieMessage() []*CrewMovieMessage {
	if x != nil {
		return x.CrewmovieMessage
	}
	return nil
}

type VideoMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *VideoMovieRequest) Reset() {
	*x = VideoMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMovieRequest) ProtoMessage() {}

func (x *VideoMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMovieRequest.ProtoReflect.Descriptor instead.
func (*VideoMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{18}
}

func (x *VideoMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type VideoMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoMessage []*VideosMessage `protobuf:"bytes,1,rep,name=video_message,json=videoMessage,proto3" json:"video_message,omitempty"`
}

func (x *VideoMovieResponse) Reset() {
	*x = VideoMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMovieResponse) ProtoMessage() {}

func (x *VideoMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMovieResponse.ProtoReflect.Descriptor instead.
func (*VideoMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{19}
}

func (x *VideoMovieResponse) GetVideoMessage() []*VideosMessage {
	if x != nil {
		return x.VideoMessage
	}
	return nil
}

var File_proto_movie_movie_proto protoreflect.FileDescriptor

var file_proto_movie_movie_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c,
	0x0a, 0x06, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x0a,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f,
	0x67, 0x6f, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x6f, 0x67, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xe2, 0x02, 0x0a, 0x0c,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x47,
	0x65, 0x6e, 0x72, 0x65, 0x73, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x6f, 0x6d, 0x65, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65,
	0x72, 0x76, 0x69, 0x65, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x76, 0x65,
	0x72, 0x76, 0x69, 0x65, 0x77, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x61, 0x63, 0x6b, 0x64, 0x72, 0x6f,
	0x70, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61,
	0x63, 0x6b, 0x64, 0x72, 0x6f, 0x70, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6d, 0x64, 0x62, 0x5f, 0x69, 0x64, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x64, 0x62, 0x49, 0x64, 0x12, 0x31, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0xbf, 0x01, 0x0a, 0x14, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x12,
	0x21, 0x0a, 0x0c, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x76, 0x6f, 0x74, 0x65, 0x41, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x76, 0x6f, 0x74, 0x65,
	0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x22, 0x77, 0x0a, 0x10, 0x43, 0x61, 0x73, 0x74, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x22, 0x6b, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x77, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6a,
	0x6f, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x22, 0x35, 0x0a,
	0x0d, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x2c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x49, 0x64, 0x22, 0x4c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x0c, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x19, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6a, 0x0a, 0x18, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x14, 0x70, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x72, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x50, 0x6f,
	0x70, 0x75, 0x6c, 0x61, 0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x13, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x40, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x17, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x13, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x12, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x2d, 0x0a, 0x10, 0x43, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64,
	0x22, 0x59, 0x0a, 0x11, 0x43, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x11, 0x63, 0x61, 0x73, 0x74, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x10, 0x63, 0x61, 0x73, 0x74, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2d, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x77, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x77, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x11, 0x63, 0x72, 0x65, 0x77, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x77, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x10, 0x63, 0x72, 0x65, 0x77, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x11, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x4f, 0x0a, 0x12, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xec, 0x04, 0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x12, 0x56, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x16, 0x2e, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x7b, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x6c, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x2e,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x70,
	0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x12, 0x76, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x7b, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x5f,
	0x0a, 0x0a, 0x43, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x43, 0x61,
	0x73, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f,
	0x63, 0x61, 0x73, 0x74, 0x2f, 0x7b, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x7d, 0x12,
	0x5f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x77, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x12, 0x17, 0x2e,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x77, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x43,
	0x72, 0x65, 0x77, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x2f, 0x63, 0x72, 0x65, 0x77, 0x2f, 0x7b, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x7d,
	0x12, 0x63, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x12,
	0x18, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x12, 0x17, 0x2f, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2f, 0x7b, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x6a, 0x61, 0x74, 0x6a, 0x72, 0x32, 0x39, 0x2f, 0x67, 0x6f, 0x2d,
	0x67, 0x72, 0x70, 0x63, 0x2d, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_movie_movie_proto_rawDescOnce sync.Once
	file_proto_movie_movie_proto_rawDescData = file_proto_movie_movie_proto_rawDesc
)

func file_proto_movie_movie_proto_rawDescGZIP() []byte {
	file_proto_movie_movie_proto_rawDescOnce.Do(func() {
		file_proto_movie_movie_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_movie_movie_proto_rawDescData)
	})
	return file_proto_movie_movie_proto_rawDescData
}

var file_proto_movie_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_movie_movie_proto_goTypes = []interface{}{
	(*Genres)(nil),                   // 0: movie.Genres
	(*Production)(nil),               // 1: movie.Production
	(*MovieMessage)(nil),             // 2: movie.MovieMessage
	(*PopularMoviesMessage)(nil),     // 3: movie.PopularMoviesMessage
	(*SearchMoviesMessage)(nil),      // 4: movie.SearchMoviesMessage
	(*CastMovieMessage)(nil),         // 5: movie.CastMovieMessage
	(*CrewMovieMessage)(nil),         // 6: movie.CrewMovieMessage
	(*VideosMessage)(nil),            // 7: movie.VideosMessage
	(*GetMovieRequest)(nil),          // 8: movie.GetMovieRequest
	(*GetMovieResponse)(nil),         // 9: movie.GetMovieResponse
	(*ListPopularMovieRequest)(nil),  // 10: movie.ListPopularMovieRequest
	(*ListPopularMovieResponse)(nil), // 11: movie.ListPopularMovieResponse
	(*ListSearchMovieRequest)(nil),   // 12: movie.ListSearchMovieRequest
	(*ListSearchMovieResponse)(nil),  // 13: movie.ListSearchMovieResponse
	(*CastMovieRequest)(nil),         // 14: movie.CastMovieRequest
	(*CastMovieResponse)(nil),        // 15: movie.CastMovieResponse
	(*CrewMovieRequest)(nil),         // 16: movie.CrewMovieRequest
	(*CrewMovieResponse)(nil),        // 17: movie.CrewMovieResponse
	(*VideoMovieRequest)(nil),        // 18: movie.VideoMovieRequest
	(*VideoMovieResponse)(nil),       // 19: movie.VideoMovieResponse
}
var file_proto_movie_movie_proto_depIdxs = []int32{
	0,  // 0: movie.MovieMessage.genres:type_name -> movie.Genres
	1,  // 1: movie.MovieMessage.production:type_name -> movie.Production
	2,  // 2: movie.GetMovieResponse.movie_message:type_name -> movie.MovieMessage
	3,  // 3: movie.ListPopularMovieResponse.popularmovie_message:type_name -> movie.PopularMoviesMessage
	4,  // 4: movie.ListSearchMovieResponse.searchmovie_message:type_name -> movie.SearchMoviesMessage
	5,  // 5: movie.CastMovieResponse.castmovie_message:type_name -> movie.CastMovieMessage
	6,  // 6: movie.CrewMovieResponse.crewmovie_message:type_name -> movie.CrewMovieMessage
	7,  // 7: movie.VideoMovieResponse.video_message:type_name -> movie.VideosMessage
	8,  // 8: movie.Movie.GetMovie:input_type -> movie.GetMovieRequest
	10, // 9: movie.Movie.ListPopularMovies:input_type -> movie.ListPopularMovieRequest
	12, // 10: movie.Movie.SearchMovies:input_type -> movie.ListSearchMovieRequest
	14, // 11: movie.Movie.CastMovies:input_type -> movie.CastMovieRequest
	16, // 12: movie.Movie.CrewMovies:input_type -> movie.CrewMovieRequest
	18, // 13: movie.Movie.VideoMovies:input_type -> movie.VideoMovieRequest
	9,  // 14: movie.Movie.GetMovie:output_type -> movie.GetMovieResponse
	11, // 15: movie.Movie.ListPopularMovies:output_type -> movie.ListPopularMovieResponse
	13, // 16: movie.Movie.SearchMovies:output_type -> movie.ListSearchMovieResponse
	15, // 17: movie.Movie.CastMovies:output_type -> movie.CastMovieResponse
	17, // 18: movie.Movie.CrewMovies:output_type -> movie.CrewMovieResponse
	19, // 19: movie.Movie.VideoMovies:output_type -> movie.VideoMovieResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_movie_movie_proto_init() }
func file_proto_movie_movie_proto_init() {
	if File_proto_movie_movie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_movie_movie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Genres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Production); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopularMoviesMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMoviesMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastMovieMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrewMovieMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideosMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPopularMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPopularMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSearchMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSearchMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrewMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrewMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_movie_movie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_movie_movie_proto_goTypes,
		DependencyIndexes: file_proto_movie_movie_proto_depIdxs,
		MessageInfos:      file_proto_movie_movie_proto_msgTypes,
	}.Build()
	File_proto_movie_movie_proto = out.File
	file_proto_movie_movie_proto_rawDesc = nil
	file_proto_movie_movie_proto_goTypes = nil
	file_proto_movie_movie_proto_depIdxs = nil
}
