// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: proto/movie/movie.proto

package movie

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovieMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId     int32  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PosterPath  string `protobuf:"bytes,3,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	ReleaseDate string `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
}

func (x *MovieMessage) Reset() {
	*x = MovieMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieMessage) ProtoMessage() {}

func (x *MovieMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieMessage.ProtoReflect.Descriptor instead.
func (*MovieMessage) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{0}
}

func (x *MovieMessage) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *MovieMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieMessage) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *MovieMessage) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

type PopularMoviesMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PosterPath  string  `protobuf:"bytes,3,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	ReleaseDate string  `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Overview    string  `protobuf:"bytes,5,opt,name=overview,proto3" json:"overview,omitempty"`
	VoteAverage float32 `protobuf:"fixed32,6,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
}

func (x *PopularMoviesMessage) Reset() {
	*x = PopularMoviesMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopularMoviesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularMoviesMessage) ProtoMessage() {}

func (x *PopularMoviesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularMoviesMessage.ProtoReflect.Descriptor instead.
func (*PopularMoviesMessage) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{1}
}

func (x *PopularMoviesMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PopularMoviesMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PopularMoviesMessage) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *PopularMoviesMessage) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *PopularMoviesMessage) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *PopularMoviesMessage) GetVoteAverage() float32 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

type SearchMoviesMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PosterPath  string  `protobuf:"bytes,3,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	ReleaseDate string  `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	VoteAverage float32 `protobuf:"fixed32,6,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
}

func (x *SearchMoviesMessage) Reset() {
	*x = SearchMoviesMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMoviesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMoviesMessage) ProtoMessage() {}

func (x *SearchMoviesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMoviesMessage.ProtoReflect.Descriptor instead.
func (*SearchMoviesMessage) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMoviesMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchMoviesMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchMoviesMessage) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *SearchMoviesMessage) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *SearchMoviesMessage) GetVoteAverage() float32 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

type GetMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId string `protobuf:"bytes,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *GetMovieRequest) Reset() {
	*x = GetMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRequest) ProtoMessage() {}

func (x *GetMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{3}
}

func (x *GetMovieRequest) GetMovieId() string {
	if x != nil {
		return x.MovieId
	}
	return ""
}

type GetMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PopularmovieMessage *MovieMessage `protobuf:"bytes,1,opt,name=popularmovie_message,json=popularmovieMessage,proto3" json:"popularmovie_message,omitempty"`
}

func (x *GetMovieResponse) Reset() {
	*x = GetMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieResponse) ProtoMessage() {}

func (x *GetMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieResponse.ProtoReflect.Descriptor instead.
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{4}
}

func (x *GetMovieResponse) GetPopularmovieMessage() *MovieMessage {
	if x != nil {
		return x.PopularmovieMessage
	}
	return nil
}

type ListPopularMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPopularMovieRequest) Reset() {
	*x = ListPopularMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPopularMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopularMovieRequest) ProtoMessage() {}

func (x *ListPopularMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopularMovieRequest.ProtoReflect.Descriptor instead.
func (*ListPopularMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{5}
}

type ListPopularMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PopularmovieMessage []*PopularMoviesMessage `protobuf:"bytes,1,rep,name=popularmovie_message,json=popularmovieMessage,proto3" json:"popularmovie_message,omitempty"`
}

func (x *ListPopularMovieResponse) Reset() {
	*x = ListPopularMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPopularMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopularMovieResponse) ProtoMessage() {}

func (x *ListPopularMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopularMovieResponse.ProtoReflect.Descriptor instead.
func (*ListPopularMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{6}
}

func (x *ListPopularMovieResponse) GetPopularmovieMessage() []*PopularMoviesMessage {
	if x != nil {
		return x.PopularmovieMessage
	}
	return nil
}

type ListSearchMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchMovieId string `protobuf:"bytes,1,opt,name=search_movie_id,json=searchMovieId,proto3" json:"search_movie_id,omitempty"`
}

func (x *ListSearchMovieRequest) Reset() {
	*x = ListSearchMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSearchMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSearchMovieRequest) ProtoMessage() {}

func (x *ListSearchMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSearchMovieRequest.ProtoReflect.Descriptor instead.
func (*ListSearchMovieRequest) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{7}
}

func (x *ListSearchMovieRequest) GetSearchMovieId() string {
	if x != nil {
		return x.SearchMovieId
	}
	return ""
}

type ListSearchMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchmovieMessage []*SearchMoviesMessage `protobuf:"bytes,1,rep,name=searchmovie_message,json=searchmovieMessage,proto3" json:"searchmovie_message,omitempty"`
}

func (x *ListSearchMovieResponse) Reset() {
	*x = ListSearchMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_movie_movie_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSearchMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSearchMovieResponse) ProtoMessage() {}

func (x *ListSearchMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_movie_movie_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSearchMovieResponse.ProtoReflect.Descriptor instead.
func (*ListSearchMovieResponse) Descriptor() ([]byte, []int) {
	return file_proto_movie_movie_proto_rawDescGZIP(), []int{8}
}

func (x *ListSearchMovieResponse) GetSearchmovieMessage() []*SearchMoviesMessage {
	if x != nil {
		return x.SearchmovieMessage
	}
	return nil
}

var File_proto_movie_movie_proto protoreflect.FileDescriptor

var file_proto_movie_movie_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83,
	0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x14, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76,
	0x69, 0x65, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72, 0x76,
	0x69, 0x65, 0x77, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x76, 0x65, 0x72,
	0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x76, 0x6f, 0x74, 0x65, 0x41,
	0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x65,
	0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x6f, 0x74, 0x65,
	0x5f, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b,
	0x76, 0x6f, 0x74, 0x65, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x22, 0x2c, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a,
	0x14, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x13, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70,
	0x75, 0x6c, 0x61, 0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x6a, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x14,
	0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x2e, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x13, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x40, 0x0a, 0x16,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x66,
	0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x13, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x12, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xc5, 0x02, 0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x12, 0x56, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x16, 0x2e, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x7b, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x6c, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x2e,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x72, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x70,
	0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x12, 0x76, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x7b, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x32,
	0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x6a, 0x61,
	0x74, 0x6a, 0x72, 0x32, 0x39, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_movie_movie_proto_rawDescOnce sync.Once
	file_proto_movie_movie_proto_rawDescData = file_proto_movie_movie_proto_rawDesc
)

func file_proto_movie_movie_proto_rawDescGZIP() []byte {
	file_proto_movie_movie_proto_rawDescOnce.Do(func() {
		file_proto_movie_movie_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_movie_movie_proto_rawDescData)
	})
	return file_proto_movie_movie_proto_rawDescData
}

var file_proto_movie_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_movie_movie_proto_goTypes = []interface{}{
	(*MovieMessage)(nil),             // 0: movie.MovieMessage
	(*PopularMoviesMessage)(nil),     // 1: movie.PopularMoviesMessage
	(*SearchMoviesMessage)(nil),      // 2: movie.SearchMoviesMessage
	(*GetMovieRequest)(nil),          // 3: movie.GetMovieRequest
	(*GetMovieResponse)(nil),         // 4: movie.GetMovieResponse
	(*ListPopularMovieRequest)(nil),  // 5: movie.ListPopularMovieRequest
	(*ListPopularMovieResponse)(nil), // 6: movie.ListPopularMovieResponse
	(*ListSearchMovieRequest)(nil),   // 7: movie.ListSearchMovieRequest
	(*ListSearchMovieResponse)(nil),  // 8: movie.ListSearchMovieResponse
}
var file_proto_movie_movie_proto_depIdxs = []int32{
	0, // 0: movie.GetMovieResponse.popularmovie_message:type_name -> movie.MovieMessage
	1, // 1: movie.ListPopularMovieResponse.popularmovie_message:type_name -> movie.PopularMoviesMessage
	2, // 2: movie.ListSearchMovieResponse.searchmovie_message:type_name -> movie.SearchMoviesMessage
	3, // 3: movie.Movie.GetMovie:input_type -> movie.GetMovieRequest
	5, // 4: movie.Movie.ListPopularMovies:input_type -> movie.ListPopularMovieRequest
	7, // 5: movie.Movie.SearchMovies:input_type -> movie.ListSearchMovieRequest
	4, // 6: movie.Movie.GetMovie:output_type -> movie.GetMovieResponse
	6, // 7: movie.Movie.ListPopularMovies:output_type -> movie.ListPopularMovieResponse
	8, // 8: movie.Movie.SearchMovies:output_type -> movie.ListSearchMovieResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_movie_movie_proto_init() }
func file_proto_movie_movie_proto_init() {
	if File_proto_movie_movie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_movie_movie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopularMoviesMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchMoviesMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPopularMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPopularMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSearchMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_movie_movie_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSearchMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_movie_movie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_movie_movie_proto_goTypes,
		DependencyIndexes: file_proto_movie_movie_proto_depIdxs,
		MessageInfos:      file_proto_movie_movie_proto_msgTypes,
	}.Build()
	File_proto_movie_movie_proto = out.File
	file_proto_movie_movie_proto_rawDesc = nil
	file_proto_movie_movie_proto_goTypes = nil
	file_proto_movie_movie_proto_depIdxs = nil
}
