// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package movie

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MovieClient is the client API for Movie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MovieClient interface {
	GetMovie(ctx context.Context, in *GetMovieRequest, opts ...grpc.CallOption) (*GetMovieResponse, error)
	ListPopularMovies(ctx context.Context, in *ListPopularMovieRequest, opts ...grpc.CallOption) (*ListPopularMovieResponse, error)
	ListPlayingMovies(ctx context.Context, in *ListPlayingMovieRequest, opts ...grpc.CallOption) (*ListPlayingMovieResponse, error)
	ListUpcomingMovies(ctx context.Context, in *ListUpcomingMovieRequest, opts ...grpc.CallOption) (*ListUpcomingMovieResponse, error)
	SearchMovies(ctx context.Context, in *ListSearchMovieRequest, opts ...grpc.CallOption) (*ListSearchMovieResponse, error)
	CastMovies(ctx context.Context, in *CastMovieRequest, opts ...grpc.CallOption) (*CastMovieResponse, error)
	CrewMovies(ctx context.Context, in *CrewMovieRequest, opts ...grpc.CallOption) (*CrewMovieResponse, error)
	VideoMovies(ctx context.Context, in *VideoMovieRequest, opts ...grpc.CallOption) (*VideoMovieResponse, error)
}

type movieClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieClient(cc grpc.ClientConnInterface) MovieClient {
	return &movieClient{cc}
}

func (c *movieClient) GetMovie(ctx context.Context, in *GetMovieRequest, opts ...grpc.CallOption) (*GetMovieResponse, error) {
	out := new(GetMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.Movie/GetMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieClient) ListPopularMovies(ctx context.Context, in *ListPopularMovieRequest, opts ...grpc.CallOption) (*ListPopularMovieResponse, error) {
	out := new(ListPopularMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.Movie/ListPopularMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieClient) ListPlayingMovies(ctx context.Context, in *ListPlayingMovieRequest, opts ...grpc.CallOption) (*ListPlayingMovieResponse, error) {
	out := new(ListPlayingMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.Movie/ListPlayingMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieClient) ListUpcomingMovies(ctx context.Context, in *ListUpcomingMovieRequest, opts ...grpc.CallOption) (*ListUpcomingMovieResponse, error) {
	out := new(ListUpcomingMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.Movie/ListUpcomingMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieClient) SearchMovies(ctx context.Context, in *ListSearchMovieRequest, opts ...grpc.CallOption) (*ListSearchMovieResponse, error) {
	out := new(ListSearchMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.Movie/SearchMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieClient) CastMovies(ctx context.Context, in *CastMovieRequest, opts ...grpc.CallOption) (*CastMovieResponse, error) {
	out := new(CastMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.Movie/CastMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieClient) CrewMovies(ctx context.Context, in *CrewMovieRequest, opts ...grpc.CallOption) (*CrewMovieResponse, error) {
	out := new(CrewMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.Movie/CrewMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *movieClient) VideoMovies(ctx context.Context, in *VideoMovieRequest, opts ...grpc.CallOption) (*VideoMovieResponse, error) {
	out := new(VideoMovieResponse)
	err := c.cc.Invoke(ctx, "/movie.Movie/VideoMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServer is the server API for Movie service.
// All implementations must embed UnimplementedMovieServer
// for forward compatibility
type MovieServer interface {
	GetMovie(context.Context, *GetMovieRequest) (*GetMovieResponse, error)
	ListPopularMovies(context.Context, *ListPopularMovieRequest) (*ListPopularMovieResponse, error)
	ListPlayingMovies(context.Context, *ListPlayingMovieRequest) (*ListPlayingMovieResponse, error)
	ListUpcomingMovies(context.Context, *ListUpcomingMovieRequest) (*ListUpcomingMovieResponse, error)
	SearchMovies(context.Context, *ListSearchMovieRequest) (*ListSearchMovieResponse, error)
	CastMovies(context.Context, *CastMovieRequest) (*CastMovieResponse, error)
	CrewMovies(context.Context, *CrewMovieRequest) (*CrewMovieResponse, error)
	VideoMovies(context.Context, *VideoMovieRequest) (*VideoMovieResponse, error)
	mustEmbedUnimplementedMovieServer()
}

// UnimplementedMovieServer must be embedded to have forward compatible implementations.
type UnimplementedMovieServer struct {
}

func (UnimplementedMovieServer) GetMovie(context.Context, *GetMovieRequest) (*GetMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovie not implemented")
}
func (UnimplementedMovieServer) ListPopularMovies(context.Context, *ListPopularMovieRequest) (*ListPopularMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPopularMovies not implemented")
}
func (UnimplementedMovieServer) ListPlayingMovies(context.Context, *ListPlayingMovieRequest) (*ListPlayingMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlayingMovies not implemented")
}
func (UnimplementedMovieServer) ListUpcomingMovies(context.Context, *ListUpcomingMovieRequest) (*ListUpcomingMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUpcomingMovies not implemented")
}
func (UnimplementedMovieServer) SearchMovies(context.Context, *ListSearchMovieRequest) (*ListSearchMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMovies not implemented")
}
func (UnimplementedMovieServer) CastMovies(context.Context, *CastMovieRequest) (*CastMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CastMovies not implemented")
}
func (UnimplementedMovieServer) CrewMovies(context.Context, *CrewMovieRequest) (*CrewMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrewMovies not implemented")
}
func (UnimplementedMovieServer) VideoMovies(context.Context, *VideoMovieRequest) (*VideoMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VideoMovies not implemented")
}
func (UnimplementedMovieServer) mustEmbedUnimplementedMovieServer() {}

// UnsafeMovieServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MovieServer will
// result in compilation errors.
type UnsafeMovieServer interface {
	mustEmbedUnimplementedMovieServer()
}

func RegisterMovieServer(s grpc.ServiceRegistrar, srv MovieServer) {
	s.RegisterService(&Movie_ServiceDesc, srv)
}

func _Movie_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.Movie/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).GetMovie(ctx, req.(*GetMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movie_ListPopularMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPopularMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).ListPopularMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.Movie/ListPopularMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).ListPopularMovies(ctx, req.(*ListPopularMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movie_ListPlayingMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlayingMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).ListPlayingMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.Movie/ListPlayingMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).ListPlayingMovies(ctx, req.(*ListPlayingMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movie_ListUpcomingMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUpcomingMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).ListUpcomingMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.Movie/ListUpcomingMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).ListUpcomingMovies(ctx, req.(*ListUpcomingMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movie_SearchMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSearchMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).SearchMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.Movie/SearchMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).SearchMovies(ctx, req.(*ListSearchMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movie_CastMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CastMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).CastMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.Movie/CastMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).CastMovies(ctx, req.(*CastMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movie_CrewMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrewMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).CrewMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.Movie/CrewMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).CrewMovies(ctx, req.(*CrewMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movie_VideoMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).VideoMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/movie.Movie/VideoMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).VideoMovies(ctx, req.(*VideoMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Movie_ServiceDesc is the grpc.ServiceDesc for Movie service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Movie_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "movie.Movie",
	HandlerType: (*MovieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovie",
			Handler:    _Movie_GetMovie_Handler,
		},
		{
			MethodName: "ListPopularMovies",
			Handler:    _Movie_ListPopularMovies_Handler,
		},
		{
			MethodName: "ListPlayingMovies",
			Handler:    _Movie_ListPlayingMovies_Handler,
		},
		{
			MethodName: "ListUpcomingMovies",
			Handler:    _Movie_ListUpcomingMovies_Handler,
		},
		{
			MethodName: "SearchMovies",
			Handler:    _Movie_SearchMovies_Handler,
		},
		{
			MethodName: "CastMovies",
			Handler:    _Movie_CastMovies_Handler,
		},
		{
			MethodName: "CrewMovies",
			Handler:    _Movie_CrewMovies_Handler,
		},
		{
			MethodName: "VideoMovies",
			Handler:    _Movie_VideoMovies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/movie/movie.proto",
}
